---

version: '3'

services:

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    build:
      context: services/caddy
      dockerfile: Dockerfile
    ports:
      - "9000:2015"
    volumes:
      - "./services/caddy/Caddyfile:/etc/Caddyfile"
    depends_on:
      - app

  app:
    # image: gcr.io/hexlet-basics/app
    build:
      context: services/app
      dockerfile: Dockerfile
    command: mix phx.server
    ports:
      - "${PORT}:${PORT}"
    env_file: '.env'
    volumes:
      - "app_node_modules:/app/node_modules"
      - "app_static:/app/priv/static"
      # - "app_build:/app/_build"
      # - "app_deps:/app/deps"
      - "./services/app:/app"
      - "~/.bash_history:/root/.bash_history:cached"
      - "./tmp/exercises-php:/exercises-php"
      - "./tmp/exercises-javascript:/exercises-javascript"
      - "./tmp/exercises-python:/exercises-python"
      - ".bashrc:/root/.bashrc:cached"
      - '/var/run/docker.sock:/var/run/docker.sock'
      # - "/var/tmp:/var/tmp:cached"
      - "/tmp:/tmp:cached"
    depends_on:
      - db

volumes:
  pgdata:
  app_node_modules:
  app_static:
  # app_build:
  # app_deps:
