---

version: '3'

services:

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    build:
      context: services/caddy
      dockerfile: Dockerfile.development
    ports:
      - "443:2015"
    volumes:
      - "./services/caddy/files/development/Caddyfile:/etc/Caddyfile"
    depends_on:
      - web

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
    command: mix phx.server
    ports:
      - "${PORT}:${PORT}"
    env_file: '.env'
    volumes:
      - "web_static:/web/priv/static"
      - "./services/web:/app"
      - "~/.bash_history:/root/.bash_history:cached"
      - "./tmp/hexletbasics:/hexletbasics"
      - ".bashrc:/root/.bashrc:cached"
      - '/var/run/docker.sock:/var/run/docker.sock'
      # - "/var/tmp:/var/tmp:cached"
      - "/tmp:/tmp"
    depends_on:
      - db

volumes:
  pgdata:
  # web_node_modules:
  web_static:
  # app_build:
  # app_deps:
