---

apiVersion: batch/v1
kind: Job
metadata:
  name: exercises-python-job
spec:

  template:
    spec:
      restartPolicy: Never

      volumes:
        - name: pod-data
          emptyDir: {}

      initContainers:
        - name: exercises-python
          image: gcr.io/hexlet-basics/exercises-python
          command:
            - cp
            - "-r"
            - "/exercises-python/."
            - "/out"
          volumeMounts:
            - mountPath: /out
              name: pod-data

      containers:

        - name: app
          imagePullPolicy: Always
          image: gcr.io/hexlet-basics/app:v104
          command:
            - mix
            - x.exercises.load
            - python
          volumeMounts:
            - mountPath: /exercises-python
              name: pod-data
          resources:
            requests:
              cpu: 10m
          envFrom:
            - secretRef:
                name: hexlet-basics-secrets
            - secretRef:
                name: cloudsql-db-credentials
            - secretRef:
                name: github-credentials
            - configMapRef:
                name: hexlet-basics-config-map
